Rename global root capabilities
CTSRD-CHERI/cheribsd pull request #847
Opened 2020-12-03 15:22 UTC by qwattash

Moved to {kernel,userspace}_*cap naming for capabilities.
I renamed the mips-specific ones by prefixing them with `mips_` as in `mips_xkseg_cap` instead of using the `kernel_*` prefix as I would not expect those to be used outside MD code.

2020-12-03 15:23 UTC, qwattash commented
Jenkins will fail because I have not merged the branch with the latest dev changes.

2020-12-03 15:26 UTC, jrtc27 requested changes

2020-12-03 15:26 UTC, jrtc27 commented on sys/cheri/cheri.h
> +extern void * __capability kernel_root_sealcap;
This duplicates the one above.

2020-12-03 17:01 UTC, brooksdavis commented on sys/riscv/cheri/cheri_machdep.c
> +        kernel_root_sealcap = ctemp;
```suggestion
	kernel_root_sealcap = ctemp;
```

2020-12-03 17:01 UTC, brooksdavis commented on sys/riscv/cheri/cheri_machdep.c
> +        kernel_root_cap = cheri_andperm(kroot,
```suggestion
	kernel_root_cap = cheri_andperm(kroot,
```

2020-12-03 19:02 UTC, qwattash commented on sys/cheri/cheri.h
> +extern void * __capability kernel_root_sealcap;
Messed up a rename, sorry about that.

2020-12-08 00:36 UTC, brooksdavis reviewed
A few small punctuation suggestions, but otherwise looks good to me.

2020-12-08 00:36 UTC, brooksdavis commented on sys/cheri/cheri_usercap.c
> + * Build a new userspace capability derived from userspace_root_cap
Removing periods from these sentences seems odd.

2020-12-08 00:36 UTC, brooksdavis commented on sys/mips/cheri/cheri.c
> +	 * Documentary assertions for userspace_root_cap  Default data and
```suggestion
	 * Documentary assertions for userspace_root_cap.  Default data and
```

2020-12-08 00:36 UTC, brooksdavis commented on sys/vm/vm_mmap.c
> +		.mr_source_cap = userspace_root_cap
```suggestion
		.mr_source_cap = userspace_root_cap,
```
style prefers trailing commas to reduce future diffs.

2020-12-16 15:39 UTC, merged